# Generated by Django 5.0.9 on 2026-03-04 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverificationtoken_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITICertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_date', models.DateField(help_text='Date CITI course was completed')),
                ('expiration_date', models.DateField(help_text='Date certificate expires (must renew before this)')),
                ('record_id', models.CharField(blank=True, help_text='CITI Record ID', max_length=50)),
                ('course_name', models.CharField(blank=True, help_text='e.g. Human Subjects Research - Student Researchers', max_length=200)),
                ('certificate_file', models.FileField(blank=True, help_text='Uploaded certificate PDF', null=True, upload_to='citi_certificates/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citi_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CITI Certificate',
                'verbose_name_plural': 'CITI Certificates',
                'db_table': 'citi_certificates',
                'ordering': ['-expiration_date'],
            },
        ),
    ]
