# Generated by Django 5.0.9 on 2026-01-13 20:20
# Updated: 0004_study runs after 0010 in merge order; all tables/columns already exist
# from 0004_irbreview, 0005, 0006, 0010. So this migration is state-only (no database ops).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_add_irb_audit_fields'),
        ('studies', '0010_protocol_submission_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='study',
                    name='involves_deception',
                    field=models.BooleanField(default=False, help_text='Protocol involves deception (requires chair review)'),
                ),
                migrations.AddField(
                    model_name='study',
                    name='is_classroom_based',
                    field=models.BooleanField(default=False, help_text='Classroom-based study (not available for general signup, IRB monitoring only)'),
                ),
                migrations.CreateModel(
                    name='CollegeRepresentative',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('college', models.CharField(choices=[('business', 'College of Business Administration'), ('education', 'College of Education and Behavioral Sciences'), ('liberal_arts', 'College of Liberal Arts'), ('sciences', 'College of Sciences & Technology'), ('nursing', 'Department of Nursing')], max_length=50, unique=True)),
                        ('is_chair', models.BooleanField(default=False, help_text='This representative is the IRB Chair')),
                        ('active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('representative', models.ForeignKey(help_text='IRB member serving as college representative', limit_choices_to={'role': 'irb_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_representative_assignments', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'College Representative',
                        'verbose_name_plural': 'College Representatives',
                        'db_table': 'college_representatives',
                        'ordering': ['college'],
                    },
                ),
                migrations.CreateModel(
                    name='IRBReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, help_text='Protocol version number')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('osf_repo_url', models.URLField(blank=True, help_text='OSF repository URL if materials are hosted there')),
                ('uploaded_files', models.JSONField(default=list, help_text='List of uploaded file metadata')),
                ('ethics_analysis', models.JSONField(blank=True, help_text='Ethics agent findings', null=True)),
                ('privacy_analysis', models.JSONField(blank=True, help_text='Privacy agent findings', null=True)),
                ('vulnerability_analysis', models.JSONField(blank=True, help_text='Vulnerable populations analysis', null=True)),
                ('data_security_analysis', models.JSONField(blank=True, help_text='Data handling and security findings', null=True)),
                ('consent_analysis', models.JSONField(blank=True, help_text='Consent adequacy analysis', null=True)),
                ('overall_risk_level', models.CharField(blank=True, choices=[('minimal', 'Minimal Risk'), ('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], help_text='Overall risk assessment', max_length=20)),
                ('critical_issues', models.JSONField(default=list, help_text='Critical ethical issues requiring immediate attention')),
                ('moderate_issues', models.JSONField(default=list, help_text='Moderate issues requiring attention')),
                ('minor_issues', models.JSONField(default=list, help_text='Minor suggestions for improvement')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable recommendations from AI analysis')),
                ('researcher_notes', models.TextField(blank=True, help_text="Researcher's response to the review")),
                ('issues_addressed', models.JSONField(default=list, help_text='List of issue IDs that have been addressed')),
                ('ai_model_versions', models.JSONField(default=dict, help_text='Track which AI models and versions were used')),
                ('processing_time_seconds', models.IntegerField(blank=True, help_text='Time taken to complete the review', null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_irb_reviews', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irb_reviews', to='studies.study')),
            ],
            options={
                'verbose_name': 'IRB Review',
                'verbose_name_plural': 'IRB Reviews',
                'db_table': 'irb_reviews',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='IRBReviewerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_email_updates', models.BooleanField(default=True, help_text='Send email notifications when there are new reviews or updates.')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time an automated notification was sent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'irb_member'}, on_delete=django.db.models.deletion.CASCADE, related_name='irb_assignments', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='studies.study')),
            ],
            options={
                'verbose_name': 'IRB Reviewer Assignment',
                'verbose_name_plural': 'IRB Reviewer Assignments',
                'db_table': 'irb_reviewer_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='irb_reviewers',
            field=models.ManyToManyField(blank=True, help_text='IRB members assigned to audit this study', related_name='assigned_irb_studies', through='studies.IRBReviewerAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProtocolSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_number', models.CharField(db_index=True, help_text='Auto-generated submission number', max_length=50, unique=True)),
                ('version', models.IntegerField(default=1, help_text='Submission version number')),
                ('pi_suggested_review_type', models.CharField(choices=[('exempt', 'Exempt'), ('expedited', 'Expedited Review'), ('full', 'Full Board Review')], help_text='Review type suggested by Primary Investigator', max_length=20)),
                ('college_rep_determination', models.CharField(blank=True, choices=[('exempt', 'Exempt'), ('expedited', 'Expedited Review'), ('full', 'Full Board Review')], help_text="College rep's determination of review type", max_length=20)),
                ('involves_deception', models.BooleanField(default=False, help_text='Protocol involves deception (requires chair review)')),
                ('review_type', models.CharField(choices=[('exempt', 'Exempt'), ('expedited', 'Expedited Review'), ('full', 'Full Board Review')], help_text='Actual review type (may differ from PI suggestion)', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revise_resubmit', 'Revise & Resubmit'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current decision status', max_length=20)),
                ('protocol_number', models.CharField(blank=True, db_index=True, help_text='IRB protocol number (issued upon approval)', max_length=100)),
                ('rejection_grounds', models.TextField(blank=True, help_text='Grounds for rejection (if rejected)')),
                ('rnr_notes', models.TextField(blank=True, help_text='Revise & resubmit notes and required changes')),
                ('approval_notes', models.TextField(blank=True, help_text='Approval notes and conditions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('ai_review', models.ForeignKey(blank=True, help_text='Optional AI-assisted review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_submission', to='studies.irbreview')),
                ('chair_reviewer', models.ForeignKey(blank=True, help_text='IRB Chair reviewing this submission', limit_choices_to={'role': 'irb_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair_reviews', to=settings.AUTH_USER_MODEL)),
                ('college_rep', models.ForeignKey(blank=True, help_text='College representative assigned to this submission', limit_choices_to={'role': 'irb_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='IRB member who made the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_protocols', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, help_text='IRB members assigned to review (for expedited reviews)', limit_choices_to={'role': 'irb_member'}, related_name='protocol_reviews', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_submissions', to='studies.study')),
                ('submitted_by', models.ForeignKey(help_text='Primary Investigator who submitted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_protocols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocol Submission',
                'verbose_name_plural': 'Protocol Submissions',
                'db_table': 'protocol_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='irb_reviews/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('protocol', 'Study Protocol'), ('consent', 'Consent Form'), ('survey', 'Survey/Questionnaire'), ('recruitment', 'Recruitment Materials'), ('debrief', 'Debriefing Materials'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(help_text='SHA256 hash for integrity verification', max_length=64)),
                ('file_size_bytes', models.IntegerField(default=0, help_text='File size in bytes')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='studies.irbreview')),
            ],
            options={
                'verbose_name': 'Review Document',
                'verbose_name_plural': 'Review Documents',
                'db_table': 'review_documents',
                'ordering': ['file_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('irb', 'IRB Reviewers'), ('team', 'Research Team Only')], db_index=True, default='irb', help_text='Choose who should see this update.', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='study_updates/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_size', models.IntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Last time IRB reviewers were emailed about this update.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_updates', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='studies.study')),
            ],
            options={
                'verbose_name': 'Study Update',
                'verbose_name_plural': 'Study Updates',
                'db_table': 'study_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['study', '-version'], name='irb_reviews_study_i_d2f567_idx'),
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['status', 'initiated_at'], name='irb_reviews_status_e20f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['overall_risk_level'], name='irb_reviews_overall_928737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='irbreview',
            unique_together={('study', 'version')},
        ),
        migrations.AddIndex(
            model_name='irbreviewerassignment',
            index=models.Index(fields=['study', 'reviewer'], name='irb_reviewe_study_i_ea07a0_idx'),
        ),
        migrations.AddIndex(
            model_name='irbreviewerassignment',
            index=models.Index(fields=['reviewer', '-created_at'], name='irb_reviewe_reviewe_dcdca2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='irbreviewerassignment',
            unique_together={('study', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='protocolsubmission',
            index=models.Index(fields=['study', '-version'], name='protocol_su_study_i_02d037_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsubmission',
            index=models.Index(fields=['decision', 'submitted_at'], name='protocol_su_decisio_3d8d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsubmission',
            index=models.Index(fields=['review_type', 'decision'], name='protocol_su_review__9f94b6_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsubmission',
            index=models.Index(fields=['college_rep', 'decision'], name='protocol_su_college_69ffc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolsubmission',
            unique_together={('study', 'version')},
        ),
        migrations.AddIndex(
            model_name='studyupdate',
            index=models.Index(fields=['study', 'visibility', '-created_at'], name='study_updat_study_i_dcf9c9_idx'),
        ),
            ],
            database_operations=[],
        ),
    ]
