# Generated by Django 5.0.9 on 2025-10-22 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_add_irb_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IRBReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, help_text='Protocol version number')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('osf_repo_url', models.URLField(blank=True, help_text='OSF repository URL if materials are hosted there')),
                ('uploaded_files', models.JSONField(default=list, help_text='List of uploaded file metadata')),
                ('ethics_analysis', models.JSONField(blank=True, help_text='Ethics agent findings', null=True)),
                ('privacy_analysis', models.JSONField(blank=True, help_text='Privacy agent findings', null=True)),
                ('vulnerability_analysis', models.JSONField(blank=True, help_text='Vulnerable populations analysis', null=True)),
                ('data_security_analysis', models.JSONField(blank=True, help_text='Data handling and security findings', null=True)),
                ('consent_analysis', models.JSONField(blank=True, help_text='Consent adequacy analysis', null=True)),
                ('overall_risk_level', models.CharField(blank=True, choices=[('minimal', 'Minimal Risk'), ('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], help_text='Overall risk assessment', max_length=20)),
                ('critical_issues', models.JSONField(default=list, help_text='Critical ethical issues requiring immediate attention')),
                ('moderate_issues', models.JSONField(default=list, help_text='Moderate issues requiring attention')),
                ('minor_issues', models.JSONField(default=list, help_text='Minor suggestions for improvement')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable recommendations from AI analysis')),
                ('researcher_notes', models.TextField(blank=True, help_text="Researcher's response to the review")),
                ('issues_addressed', models.JSONField(default=list, help_text='List of issue IDs that have been addressed')),
                ('ai_model_versions', models.JSONField(default=dict, help_text='Track which AI models and versions were used')),
                ('processing_time_seconds', models.IntegerField(blank=True, help_text='Time taken to complete the review', null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_irb_reviews', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irb_reviews', to='studies.study')),
            ],
            options={
                'verbose_name': 'IRB Review',
                'verbose_name_plural': 'IRB Reviews',
                'db_table': 'irb_reviews',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='irb_reviews/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('protocol', 'Study Protocol'), ('consent', 'Consent Form'), ('survey', 'Survey/Questionnaire'), ('recruitment', 'Recruitment Materials'), ('debrief', 'Debriefing Materials'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(help_text='SHA256 hash for integrity verification', max_length=64)),
                ('file_size_bytes', models.IntegerField(default=0, help_text='File size in bytes')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='studies.irbreview')),
            ],
            options={
                'verbose_name': 'Review Document',
                'verbose_name_plural': 'Review Documents',
                'db_table': 'review_documents',
                'ordering': ['file_type', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['study', '-version'], name='irb_reviews_study_i_d2f567_idx'),
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['status', 'initiated_at'], name='irb_reviews_status_e20f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='irbreview',
            index=models.Index(fields=['overall_risk_level'], name='irb_reviews_overall_928737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='irbreview',
            unique_together={('study', 'version')},
        ),
    ]
