# Generated by Django 5.0.9 on 2026-01-06 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_protocol_submission_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='irbreviewerassignment',
            name='irb_assign_reviewer_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='protocolsubmission',
            name='protocol_s_study_version_idx',
        ),
        migrations.RenameIndex(
            model_name='irbreviewerassignment',
            new_name='irb_reviewe_study_i_ea07a0_idx',
            old_name='irb_assign_study_reviewer_idx',
        ),
        migrations.RenameIndex(
            model_name='protocolsubmission',
            new_name='protocol_su_decisio_3d8d8d_idx',
            old_name='protocol_s_decision_submitted_idx',
        ),
        migrations.RenameIndex(
            model_name='protocolsubmission',
            new_name='protocol_su_review__9f94b6_idx',
            old_name='protocol_s_review_type_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='protocolsubmission',
            new_name='protocol_su_college_69ffc3_idx',
            old_name='protocol_s_college_rep_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='studyupdate',
            new_name='study_updat_study_i_dcf9c9_idx',
            old_name='study_upda_study_v_1a55b4_idx',
        ),
        migrations.AddIndex(
            model_name='irbreviewerassignment',
            index=models.Index(fields=['reviewer', '-created_at'], name='irb_reviewe_reviewe_dcdca2_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsubmission',
            index=models.Index(fields=['study', '-version'], name='protocol_su_study_i_02d037_idx'),
        ),
    ]
