# Generated by Django 5.0.9 on 2026-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_remove_irbreviewerassignment_irb_assign_reviewer_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_classroom_based',
            field=models.BooleanField(default=False, help_text='Classroom-based study (not available for general signup, IRB monitoring only)'),
        ),
    ]
