# Generated by Django 5.0.9 on 2026-01-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_involves_deception_study_is_classroom_based_and_more'),
        ('studies', '0012_study_is_classroom_based'),
    ]

    operations = [
    ]
