# Generated by Django 5.0.9 on 2026-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_merge_20260113_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='benefits_to_others',
            field=models.TextField(blank=True, help_text='Benefits to individuals who are not subjects but may have similar problems'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='benefits_to_society',
            field=models.TextField(blank=True, help_text='Benefits to society in general'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='benefits_to_subjects',
            field=models.TextField(blank=True, help_text='Benefits to the human subjects involved'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='confidentiality_procedures',
            field=models.TextField(blank=True, help_text='Procedures for maintaining confidentiality or anonymity'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='consent_procedures',
            field=models.TextField(blank=True, help_text='How informed consent will be obtained from participants'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='continuation_of_previous',
            field=models.BooleanField(default=False, help_text='Is this project a continuation of research previously approved by the HSIRB?'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='costs_to_subjects',
            field=models.TextField(blank=True, help_text='Costs to subjects (time, money, repeated testing, etc.)'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_access',
            field=models.TextField(blank=True, help_text='Who will have access to the data'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_collection_methods',
            field=models.TextField(blank=True, help_text='Detailed description of data collection methods and instruments'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_retention',
            field=models.TextField(blank=True, help_text='Data retention policy and timeline'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_storage',
            field=models.TextField(blank=True, help_text='How data will be stored and secured'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='educational_justification',
            field=models.TextField(blank=True, help_text='Educational justification (if this is an educational exercise)'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='estimated_completion_date',
            field=models.CharField(blank=True, help_text='Estimated completion date', max_length=100),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='estimated_start_date',
            field=models.CharField(blank=True, help_text='Estimated starting date', max_length=100),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='exclusion_criteria',
            field=models.TextField(blank=True, help_text='Criteria for excluding subjects'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='exemption_category',
            field=models.CharField(blank=True, help_text='Exemption category (if requesting exempt status)', max_length=100),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='expedited_category',
            field=models.CharField(blank=True, help_text='Expedited review category (if requesting expedited review)', max_length=100),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='funding_source',
            field=models.TextField(blank=True, help_text='Source of project funds'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='inclusion_criteria',
            field=models.TextField(blank=True, help_text='Criteria for including subjects'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='payment_compensation',
            field=models.TextField(blank=True, help_text='Payment or compensation provided to participants'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='population_description',
            field=models.TextField(blank=True, help_text='Description of the population of human subjects'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='previous_protocol_number',
            field=models.CharField(blank=True, help_text='Previous HSIRB protocol number (if continuation)', max_length=100),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='protocol_description',
            field=models.TextField(blank=True, help_text='Detailed description of the research project or proposal'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='recruitment_method',
            field=models.TextField(blank=True, help_text='How will you recruit subjects?'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='recruitment_script',
            field=models.TextField(blank=True, help_text='Recruitment script or materials'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='research_objectives',
            field=models.TextField(blank=True, help_text='Primary research objectives and goals'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='research_procedures',
            field=models.TextField(blank=True, help_text='Detailed research procedures and data collection methods'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='research_questions',
            field=models.TextField(blank=True, help_text='Research questions or hypotheses (if applicable)'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='review_type_justification',
            field=models.TextField(blank=True, help_text='Basis for requesting exemption, expedited review, or full board review'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='risk_mitigation',
            field=models.TextField(blank=True, help_text='Risk mitigation strategies and protections for participants'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='risk_statement',
            field=models.TextField(blank=True, help_text='Statement of risk - describe any physical, emotional, social, or legal risks'),
        ),
    ]
