# Generated by Django 5.0.9 on 2026-01-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_add_detailed_protocol_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='appendices_notes',
            field=models.TextField(blank=True, help_text='Notes about supporting documents, instruments, or analysis plans attached'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='citi_training_completion',
            field=models.TextField(blank=True, help_text='CITI training completion dates and certificate numbers for all investigators'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='co_investigator_signatures',
            field=models.TextField(blank=True, help_text='Co-investigator signatures and dates'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='co_investigators',
            field=models.TextField(blank=True, help_text='List of co-investigators (name, title, department, email)'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='cultural_considerations',
            field=models.TextField(blank=True, help_text='Cultural considerations and adaptations for international research'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_monitoring_plan',
            field=models.TextField(blank=True, help_text='Plan for monitoring data collection and quality assurance'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='data_sharing_plan',
            field=models.TextField(blank=True, help_text='Plan for sharing data with other researchers or repositories'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='department_chair_signature_date',
            field=models.DateTimeField(blank=True, help_text='Date department chair signed (if required)', null=True),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='financial_interest_disclosure',
            field=models.TextField(blank=True, help_text='Disclosure of any financial interests or conflicts of interest'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='financial_interest_none',
            field=models.BooleanField(default=False, help_text='No financial interests to disclose'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='international_research_locations',
            field=models.TextField(blank=True, help_text='Geographic locations where research will be conducted'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='involves_international_research',
            field=models.BooleanField(default=False, help_text='Does this research involve international participants or locations?'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='involves_vulnerable_populations',
            field=models.BooleanField(default=False, help_text='Does this research involve vulnerable populations?'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='irb_contact_notes',
            field=models.TextField(blank=True, help_text='Additional IRB contact information or notes'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='oversight_procedures',
            field=models.TextField(blank=True, help_text='Procedures for oversight and quality assurance'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='participant_access_to_results',
            field=models.TextField(blank=True, help_text='How participants can access study results (if applicable)'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_department',
            field=models.CharField(blank=True, help_text='PI department', max_length=200),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_email',
            field=models.EmailField(blank=True, help_text='PI email address', max_length=254),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_name',
            field=models.CharField(blank=True, help_text='Primary Investigator full name', max_length=200),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_phone',
            field=models.CharField(blank=True, help_text='PI phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_signature_date',
            field=models.DateTimeField(blank=True, help_text='Date PI signed the submission', null=True),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='pi_title',
            field=models.CharField(blank=True, help_text='PI title/position', max_length=200),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='publication_plan',
            field=models.TextField(blank=True, help_text='Plan for publication and dissemination of results'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='study_contact_email',
            field=models.EmailField(blank=True, help_text='Study contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='study_contact_name',
            field=models.CharField(blank=True, help_text='Study contact person name (if different from PI)', max_length=200),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='study_contact_phone',
            field=models.CharField(blank=True, help_text='Study contact phone', max_length=50),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='vulnerable_population_protections',
            field=models.TextField(blank=True, help_text='Specific protections and safeguards for vulnerable populations'),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='vulnerable_populations_description',
            field=models.TextField(blank=True, help_text='Describe which vulnerable populations are involved and protections in place'),
        ),
    ]
