# Generated by Django 5.0.9 on 2026-01-16 17:58

from django.db import migrations, models


def set_existing_submissions_to_submitted(apps, schema_editor):
    """Set all existing protocol submissions to 'submitted' status."""
    ProtocolSubmission = apps.get_model('studies', 'ProtocolSubmission')
    # All existing submissions should be marked as submitted (they have submission numbers)
    ProtocolSubmission.objects.filter(submission_number__isnull=False).update(status='submitted')


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0015_add_comprehensive_irb_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irbreview',
            options={'ordering': ['-initiated_at'], 'verbose_name': 'AI IRB Review', 'verbose_name_plural': 'AI IRB Reviews'},
        ),
        migrations.AlterModelOptions(
            name='protocolsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'IRB Protocol Submission', 'verbose_name_plural': 'IRB Protocol Submissions'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Response', 'verbose_name_plural': 'Study Responses'},
        ),
        migrations.AlterModelOptions(
            name='reviewdocument',
            options={'ordering': ['file_type', 'uploaded_at'], 'verbose_name': 'IRB Review Document', 'verbose_name_plural': 'IRB Review Documents'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['-booked_at'], 'verbose_name': 'Participant Signup', 'verbose_name_plural': 'Participant Signups'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-created_at'], 'verbose_name': 'Research Study', 'verbose_name_plural': 'Research Studies'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['starts_at'], 'verbose_name': 'Study Timeslot', 'verbose_name_plural': 'Study Timeslots'},
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='draft', help_text='Whether this is a draft or has been submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='protocolsubmission',
            name='submission_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated submission number (only for submitted protocols)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='protocolsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When protocol was submitted (not when draft was created)', null=True),
        ),
        migrations.RunPython(set_existing_submissions_to_submitted, migrations.RunPython.noop),
    ]
