# Generated by Django 5.0.9 on 2026-01-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_add_protocol_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='suggested_reviewers',
            field=models.TextField(blank=True, help_text="PI's suggestions for reviewers (informational - college representative will make final assignment)"),
        ),
    ]
