# Generated by Django 5.0.9 on 2026-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_add_suggested_reviewers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='citi_training_certificate',
            field=models.FileField(blank=True, help_text='Upload CITI training certificate(s) for all investigators', null=True, upload_to='protocol_submissions/citi_certificates/%Y/%m/'),
        ),
    ]
