# Generated by Django 5.0.9 on 2026-02-05 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_add_citi_certificate_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated amendment number', max_length=50, null=True, unique=True)),
                ('amendment_type', models.CharField(choices=[('minor', 'Minor Amendment'), ('major', 'Major Amendment')], default='minor', help_text='Type of amendment', max_length=20)),
                ('title', models.CharField(help_text='Brief title of the amendment', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the proposed changes')),
                ('justification', models.TextField(help_text='Justification for the proposed changes')),
                ('impact_on_risk', models.TextField(blank=True, help_text='How does this amendment impact the risk level of the study?')),
                ('impact_on_consent', models.TextField(blank=True, help_text='Does this amendment require changes to the consent form?')),
                ('new_instruments', models.TextField(blank=True, help_text='Description of any new instruments, measures, or assessments being added')),
                ('instrument_url', models.URLField(blank=True, help_text='URL to the instrument or assessment (if applicable)')),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document (e.g., updated protocol, new instrument)', null=True, upload_to='protocol_submissions/amendments/%Y/%m/')),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revise_resubmit', 'Revise & Resubmit'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Reviewer notes / approval conditions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol_submission', models.ForeignKey(help_text='The approved protocol being amended', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='studies.protocolsubmission')),
                ('reviewer', models.ForeignKey(blank=True, help_text='IRB reviewer assigned to this amendment', limit_choices_to={'role': 'irb_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocol Amendment',
                'verbose_name_plural': 'Protocol Amendments',
                'db_table': 'protocol_amendments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
