# Generated by Django 5.0.9 on 2026-03-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_add_student_data_consent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentdataconsent',
            new_name='student_dat_study_i_a198e7_idx',
            old_name='student_dat_study_i_consent_idx',
        ),
        migrations.RenameIndex(
            model_name='studyemailcontact',
            new_name='study_email_study_i_30b173_idx',
            old_name='study_email_study_i_8a1b2c_idx',
        ),
    ]
