# Generated by Django 5.0.9 on 2026-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0029_enable_hr_sjt_infographic_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='full_protocol_pdf',
            field=models.FileField(blank=True, help_text='Full set of protocols as a single PDF for IRB review (electronic version can also be viewed on the study protocol pages)', null=True, upload_to='protocol_submissions/full_protocols/%Y/%m/'),
        ),
    ]
