# Generated by Django 5.0.9 on 2026-03-16 14:30

from django.conf import settings
from django.db import migrations, models


def backfill_co_investigators_extra(apps, schema_editor):
    """Preserve existing co_investigators text into co_investigators_extra."""
    ProtocolSubmission = apps.get_model('studies', 'ProtocolSubmission')
    for sub in ProtocolSubmission.objects.all():
        if sub.co_investigators and sub.co_investigators.strip():
            sub.co_investigators_extra = sub.co_investigators.strip()
            sub.save(update_fields=['co_investigators_extra'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_add_college_rep_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='co_investigator_users',
            field=models.ManyToManyField(blank=True, help_text="PRAMS users listed as co-investigators; they will see this protocol's study on their dashboard", related_name='co_investigator_protocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolsubmission',
            name='co_investigators_extra',
            field=models.TextField(blank=True, help_text='Additional co-investigators (name, email) without PRAMS accounts; merged into co_investigators for display'),
        ),
        migrations.RunPython(backfill_co_investigators_extra, noop),
    ]
