# Generated by Django 5.0.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0033_add_co_investigator_users_and_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsubmission',
            name='primary_study_context',
            field=models.CharField(
                blank=True,
                choices=[
                    ('social_behavioral', 'Traditional social / behavioral science (surveys, qualitative, educational, CBPR, etc.)'),
                    ('biomedical_clinical', 'Biomedical or clinical intervention (drugs, devices, physical procedures)'),
                    ('mixed_other', 'Mixed or other'),
                ],
                help_text="PI classification so reviewers can apply the appropriate mental model (proportional social/behavioral vs standard IRB framework)",
                max_length=30,
            ),
        ),
    ]
