# Generated by Django 5.0.9 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0034_add_primary_study_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="reminder_24h_sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="signup",
            name="reminder_2h_sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google Calendar event id used for one-way sync",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="google_calendar_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful Google Calendar sync time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="google_calendar_sync_error",
            field=models.TextField(
                blank=True,
                help_text="Last Google Calendar sync error message",
            ),
        ),
    ]
