# Generated by Django 5.0.9 on 2026-02-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Course Enrollment', 'verbose_name_plural': 'Course Enrollments'},
        ),
    ]
